list:
    hyacinth-macaw --list


choose:
    #!/bin/bash
    hyacinth-macaw --choose


run_post_install:
    #!/bin/bash
    bash -x /usr/immutablue-build-hyacinth-macaw/post_install.sh


update_dotfiles:
    #!/bin/bash
    set -euxo pipefail

    cd "$HOME/.dotfiles"
    git pull
    stow .


clone_projects:
    #!/bin/bash
    set -euxo pipefail

    proj_dir="$HOME/Source/Projects"
    mkdir -p "${proj_dir}"
    cd "${proj_dir}"

    declare -a repos=(
        "git@gitlab.com:immutablue/immutablue.git"
        "git@gitlab.com:immutablue/immutablue-custom.git"
        "git@gitlab.com:immutablue/immutablue-cyan.git"
        "git@gitlab.com:immutablue/immutablue-asahi.git"
        "git@gitlab.com:immutablue/hyacinth-macaw.git"
        "git@gitlab.com:immutablue/immutablue-nucleus.git"
        "git@gitlab.com:zachpodbielniak/MediaTranscodePipelineNG.git"
        "git@gitlab.com:zachpodbielniak/NautilusOpenWithCode.git"
    )

    for repo in ${repos[@]}
    do 
        git clone $repo 
        git_dir=(${repo//\// })
        cd "${git_dir[1]:0:-4}"
        git fetch --all
        cd ..
    done


clone_source:
    #!/bin/bash
    set -euxo pipefail

    proj_dir="$HOME/Source/Public"
    mkdir -p "${proj_dir}"
    cd "${proj_dir}"

    declare -a repos=(
        "https://github.com/ublue-os/bazzite"
        "https://github.com/ublue-os/bluefin"
        "https://github.com/ublue-os/main"
        "https://github.com/ublue-os/config"
        "https://github.com/Dynatrace/dynatrace-operator"
        "git://gcc.gnu.org/git/gcc.git"
        "https://gitlab.gnome.org/GNOME/glib"
        "https://sourceware.org/git/glibc.git"
        "https://github.com/torvalds/linux"
    )

    for repo in ${repos[@]}
    do 
        git clone $repo 
    done


