# This sysctl conf is part of the Hyacinth Macaw project (part of Immutablue).
# Please see https://gitlab.com/immutablue/hyacinth-macaw for more details
#
#
# Set unpriv'd start range to port >= 80
net.ipv4.ip_unprivileged_port_start = 80

