[org/gnome/shell]
# List all extensions that you want to have enabled for all users
enabled-extensions=["appindicatorsupport@rgcjonas.gmail.com", "dash-to-dock@micxgx.gmail.com", "gsconnect@andyholmes.github.io", "user-theme@gnome-shell-extensions.gcampax.github.com", "desktop-cube@schneegans.github.com", "search-light@icedman.github.com", "tailscale-status@maxgallup.github.com", "tiling-assistant@leleat-on-github", "unblank@sun.wxg@gmail.com"]

# Disabled as its slow on arm64 "rounded-window-corners@fxgn"

disabled-extensions=["launch-new-instance@gnome-shell-extensions.gcampax.github.com","window-list@gnome-shell-extensions.gcampax.github.com"]
