# Set default GTK theme
[org/gnome/desktop/interface]
gtk-theme="WhiteSur-Dark"


# set buttons to left 
[org/gnome/desktop/wm/preferences]
button-layout="close,minimize,maximize:appmenu"


# set dark mode 
[org/gnome/desktop/interface]
color-scheme="prefer-dark"

